%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1
num_of_cam: 2

is_fisheye: 1
# imu_topic: "/dji_sdk_1/dji_sdk/imu"
# image0_topic: "/stereo/left/image_raw"
# image1_topic: "/stereo/right/image_raw"
imu_topic: "/mavros/imu/data"
image0_topic: "/rgb1"
image1_topic: "/rgb2"
output_path: "/home/shen/output"

depth_config: "depth_cpu.yaml"
# cam0_calib: "up.yaml"
# cam1_calib: "down.yaml"
cam0_calib: "imx219_camera_calib_1.yaml"
cam1_calib: "imx219_camera_calib_2.yaml"
image_width: 300  # For fisheye, this indicate the flattened image width; min 100; 300 - 500 is good for vins
image_height: 225
show_width: 1920

fisheye_fov_h: 220
fisheye_fov_v: 195

enable_up_top: 1
enable_down_top: 1
enable_up_side: 1
enable_down_side: 1  
enable_rear_side: 0
thres_outlier : 5
tri_max_err: 3
# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0      # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [
        0.99786418, -0.0618187, 0.02110763, 0.01000285,
        0.06162136, 0.99805074, 0.00987548, 0.01174838,
        -0.02167697, -0.0085537, 0.99972843, 0.05384881,
        0,0,0,1 ]
body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [
        0.99977697, 0.0205201, -0.00499313, -0.00323944,
        0.02057295, -0.99973029, 0.01077482, 0.00694013,
        -0.00477069, -0.01087514, -0.99992948, 0.01754524,
        0,0,0,1]


pub_flatten: 1
flatten_color: 0
warn_imu_freq: 0
imu_freq: 320
image_freq: 20

multiple_thread: 1
#Gpu accleration support

use_vxworks: 0
use_gpu: 1

enable_depth: 0 # If estimate depth cloud; only available for dual fisheye now
rgb_depth_cloud: 0 # -1: point no texture,  0 depth cloud will be gray, 1 depth cloud will be colored;
#Note that textured and colored depth cloud will slow down whole system

depth_estimate_baseline: 0.05
top_cnt: 60
side_cnt: 200
max_solve_cnt: 300 # Max Point for solve; highly influence performace

# min_dist: 20            # min distance between two features, this is for GFTT
min_dist: 20            # for vworks
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 3.0        # ransac threshold (pixel)
show_track: 1          # publish tracking image as topic
show_track_id: 1
flow_back: 0           # perform forward and backward optical flow to improve feature tracking accuracy
enable_perf_output: 0

#optimization parameters
max_solver_time: 0.04 # max solver itration time (ms), to guarantee real time
max_num_iterations: 9   # max solver itrations, to guarantee real time
# max_solver_time: 1.0  # max solver itration time (ms), to guarantee real time
# max_num_iterations: 100   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.001        # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.85         # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
# td: -0.0736        #-0.0736 when use DJI IMU                       # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)#
td: 0.014686 #Use mynteye imu
#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/shen/output/pose_graph/" # save and load path
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 

#rectify
publish_rectify: 0              # whether publish rectified pose
cam0_rectify: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1, 0, 0,
         0, 1, 0,
         0, 0, 1 ]

cam1_rectify: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1, 0, 0,
         0, 1, 0,
         0, 0, 1 ]

rolling_shutter: 0
rolling_shutter_tr: 0.04685
